version: "3.9"
services:
  web:
    build: .
    image: 954976297775.dkr.ecr.ap-northeast-2.amazonaws.com/simple-docker-service-0ace5acaf2a1
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: "0"
      DATABASE: "postgres"
      DB_ENGINE: "django.db.backends.postgresql"
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      # 중요: DB_HOST를 RDS 엔드포인트로 변경 (예시: my-rds-endpoint.amazonaws.com)
      DB_HOST: ${RDS_HOST}
      DB_PORT: "5432"
      SERVICE_TYPE: "web"
    depends_on:
      - redis # db 제거했으므로 db 의존성 제거, redis만 남김
    restart: always

  redis:
    image: redis:7-alpine
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/home/app/static # volumes 경로 유지
      - media_volume:/home/app/media  # volumes 경로 유지
    depends_on:
      - web
    restart: always

  celery-worker:
    build: .
    image: 954976297775.dkr.ecr.ap-northeast-2.amazonaws.com/simple-docker-service-0ace5acaf2a1
    volumes:
      - .:/app # celery worker volumes 유지 (필요에 따라 제거 고려)
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: "0"
      DATABASE: "postgres"
      DB_ENGINE: "django.db.backends.postgresql"
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      # 중요: DB_HOST를 RDS 엔드포인트로 변경 (예시: my-rds-endpoint.amazonaws.com)
      DB_HOST: ${RDS_HOST}
      DB_PORT: "5432"
      SERVICE_TYPE: "celery-worker"
    depends_on:
      - redis # db 제거했으므로 db 의존성 제거, redis만 남김
    restart: always

  celery-beat:
    build: .
    image: 954976297775.dkr.ecr.ap-northeast-2.amazonaws.com/simple-docker-service-0ace5acaf2a1
    volumes:
      - .:/app # celery beat volumes 유지 (필요에 따라 제거 고려)
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: "0"
      DATABASE: "postgres"
      DB_ENGINE: "django.db.backends.postgresql"
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      # 중요: DB_HOST를 RDS 엔드포인트로 변경 (예시: my-rds-endpoint.amazonaws.com)
      DB_HOST: ${RDS_HOST}
      DB_PORT: "5432"
      SERVICE_TYPE: "celery-beat"
    depends_on:
      - redis # db 제거했으므로 db 의존성 제거, redis만 남김
    restart: always

volumes:
  static_volume:
  media_volume:
  postgres_data: # 더 이상 사용하지 않으므로 제거 가능