branch-defaults:
  develop_6:
    environment: null
  main:
    environment: null
    group_suffix: null
global:
  application_name: nooridal
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Docker
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
