# Generated by Django 4.2 on 2025-03-06 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=0, max_length=15, unique=True, verbose_name='전화번호'),
            preserve_default=False,
        ),
    ]
