# Generated by Django 4.2 on 2025-03-04 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.CreateModel(
            name='Pregnancy',
            fields=[
                ('pregnancy_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('husband_id', models.UUIDField(blank=True, null=True)),
                ('baby_name', models.CharField(blank=True, max_length=100, null=True)),
                ('due_date', models.DateField()),
                ('current_week', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('high_risk', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pregnancies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '임신 정보',
                'verbose_name_plural': '임신 정보',
                'ordering': ['-created_at'],
            },
        ),
    ]
