# Generated by Django 4.2 on 2025-03-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_pregnancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregnancy',
            name='baby_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='태명'),
        ),
        migrations.AlterField(
            model_name='pregnancy',
            name='current_week',
            field=models.IntegerField(blank=True, null=True, verbose_name='현재 임신 주차'),
        ),
        migrations.AlterField(
            model_name='pregnancy',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='출산 예정일'),
        ),
        migrations.AlterField(
            model_name='pregnancy',
            name='high_risk',
            field=models.BooleanField(default=False, verbose_name='고위험 임신 여부'),
        ),
    ]
