# Generated by Django 4.2 on 2025-03-05 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options'),
        ('accounts', '0003_alter_pregnancy_baby_name_and_more'),
    ]

    operations = [
    ]
