# Generated by Django 4.2 on 2025-03-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_email_alter_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(error_messages={'blank': '전화번호를 입력해주세요.', 'invalid': '올바른 전화번호 형식이 아닙니다.', 'max_length': '전화번호는 15자를 초과할 수 없습니다.', 'unique': '이미 등록된 전화번호입니다.'}, max_length=15, unique=True, verbose_name='전화번호'),
        ),
    ]
