# Generated by Django 5.1.6 on 2025-03-07 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_groups_alter_user_user_permissions_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassworduser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='비밀번호 재설정 사용자가 속한 그룹', related_name='reset_password_user_groups', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='resetpassworduser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='비밀번호 재설정 사용자의 권한', related_name='reset_password_user_permissions', to='auth.permission'),
        ),
    ]
