# Generated by Django 4.2 on 2025-03-01 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LLMConversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="대화 고유 식별자 (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "query",
                    models.TextField(
                        help_text="사용자가 입력한 질문 내용",
                        verbose_name="사용자 질문",
                    ),
                ),
                (
                    "response",
                    models.TextField(
                        help_text="LLM이 생성한 응답 내용", verbose_name="LLM 응답"
                    ),
                ),
                (
                    "query_type",
                    models.CharField(
                        default="general",
                        help_text="질문의 유형 (예: general, nutrition, medical)",
                        max_length=50,
                        verbose_name="질문 유형",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="대화 관련 추가 정보 (키워드, 후속 질문, 사용자 정보 등)",
                        verbose_name="메타데이터",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="대화가 생성된 시간",
                        verbose_name="생성 시간",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="대화를 생성한 사용자 (null 가능)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="llm_conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "LLM 대화",
                "verbose_name_plural": "LLM 대화 목록",
                "ordering": ["-created_at"],
            },
        ),
    ]
