# Generated by Django 4.2 on 2025-03-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmconversation",
            name="source_documents",
            field=models.JSONField(blank=True, default=list, verbose_name="참조 문서"),
        ),
        migrations.AddField(
            model_name="llmconversation",
            name="using_rag",
            field=models.BooleanField(default=False, verbose_name="RAG 사용 여부"),
        ),
    ]
