# Generated by Django 4.2 on 2025-03-01 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llm", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="llmconversation",
            name="metadata",
        ),
        migrations.AddField(
            model_name="llmconversation",
            name="keywords",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="질문에서 추출된 키워드",
                verbose_name="키워드",
            ),
        ),
        migrations.AddField(
            model_name="llmconversation",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="대화가 마지막으로 수정된 시간",
                verbose_name="수정 시간",
            ),
        ),
        migrations.AddField(
            model_name="llmconversation",
            name="user_info",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="대화 시점의 사용자 정보 (임신 여부, 임신 주차 등)",
                verbose_name="사용자 정보",
            ),
        ),
    ]
