# Generated by Django 4.2 on 2025-03-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llm", "0002_llmconversation_source_documents_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmconversation",
            name="chat_id",
            field=models.UUIDField(blank=True, null=True, verbose_name="채팅 ID"),
        ),
    ]
