# Generated by Django 4.2 on 2025-03-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llm", "0002_remove_llmconversation_metadata_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="llmconversation",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="대화가 생성된 시간",
                verbose_name="생성 시간",
            ),
        ),
        migrations.AlterField(
            model_name="llmconversation",
            name="query_type",
            field=models.CharField(
                db_index=True,
                default="general",
                help_text="질문의 유형 (예: general, nutrition, medical)",
                max_length=50,
                verbose_name="질문 유형",
            ),
        ),
        migrations.AddIndex(
            model_name="llmconversation",
            index=models.Index(
                fields=["user", "query_type"], name="llm_llmconv_user_id_66d8d9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="llmconversation",
            index=models.Index(
                fields=["user", "-created_at"], name="llm_llmconv_user_id_8782c9_idx"
            ),
        ),
    ]
