# Generated by Django 4.2 on 2025-03-01 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("llm", "0004_alter_llmconversation_user"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="llmconversation",
            name="llm_llmconv_user_id_66d8d9_idx",
        ),
        migrations.RemoveField(
            model_name="llmconversation",
            name="keywords",
        ),
        migrations.RemoveField(
            model_name="llmconversation",
            name="query_type",
        ),
    ]
