# Generated by Django 4.2 on 2025-03-07 08:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmbeddingFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(help_text='파일 이름', max_length=255)),
                ('file_path', models.CharField(help_text='파일 경로', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일')),
            ],
            options={
                'verbose_name': '임베딩 파일',
                'verbose_name_plural': '임베딩 파일',
            },
        ),
    ]
