# Generated by Django 4.2 on 2025-03-01 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("llm", "0003_alter_llmconversation_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="llmconversation",
            name="user",
            field=models.ForeignKey(
                default=1,
                help_text="대화를 생성한 사용자",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="llm_conversations",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
