# Generated by Django 4.2 on 2025-03-01 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("llm", "0005_remove_llmconversation_llm_llmconv_user_id_66d8d9_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="llmconversation",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="대화를 생성한 사용자",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="llm_conversations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
